name: Deploy Notion Finance

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Streamlit secrets
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p ~/.streamlit
            cat > ~/.streamlit/secrets.toml <<EOF
            ${{ secrets.STREAMLIT_SECRETS_TOML }}
            EOF
            chmod 700 ~/.streamlit
            chmod 600 ~/.streamlit/secrets.toml

      - name: Pull latest code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            if [ -d ~/notion-finance ]; then
              cd ~/notion-finance
              git fetch origin main
              git reset --hard origin/main
            else
              git clone https://github.com/adrianlopezlanchares/notion-finance.git ~/notion-finance
            fi

      - name: Rebuild and restart Docker containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/notion-finance
            docker compose -f deployment/docker-compose.yml down
            docker compose -f deployment/docker-compose.yml up --build -d
