name: Deploy Notion Finance

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: SSH & Deploy with Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Create streamlit secrets if necessary
            mkdir -p ~/.streamlit
            cat > ~/.streamlit/secrets.toml <<EOF
            ${{ secrets.STREAMLIT_SECRETS_TOML }}
            EOF
            chmod 700 ~/.streamlit
            chmod 600 ~/.streamlit/secrets.toml

            # Pull the latest code
            if [ -d ~/notion-finance ]; then
              cd ~/notion-finance

              # Debug
              echo "Current directory: $(pwd)"
              ls -la
              git fetch origin main
              git reset --hard origin/main
            else
              git clone https://github.com/adrianlopezlanchares/notion-finance.git ~/notion-finance
              cd ~/notion-finance

              # Debug
              echo "Current directory: $(pwd)"
              ls -la
            fi

            # Rebuild and restart the Docker container
            cd ~/notion-finance
            docker compose -f deployment/docker-compose.yml down
            docker compose -f deployment/docker-compose.yml up --build -d
