name: Deploy Notion Finance

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted   # Runs directly on your VPN server
    steps:
      # 1. Pull the latest code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Create Streamlit secrets file locally
      - name: Create Streamlit secrets
        run: |
          mkdir -p ~/.streamlit
          cat > ~/.streamlit/secrets.toml <<EOF
          ${{ secrets.STREAMLIT_SECRETS_TOML }}
          EOF
          chmod 700 ~/.streamlit
          chmod 600 ~/.streamlit/secrets.toml

      # 3. Rebuild and restart Docker containers locally
      - name: Rebuild and restart Docker containers
        run: |
          docker compose -f deployment/docker-compose.yml down
          docker compose -f deployment/docker-compose.yml up --build -d
